*&---------------------------------------------------------------------*
*& Include              ZINZMM01_S01
*&---------------------------------------------------------------------*
*&           S E L E C T I O N  - S C R E E N
*&---------------------------------------------------------------------*

TABLES: mara, mard, marc.
TABLES: sscrfields.
TYPE-POOLS: icon.
SELECTION-SCREEN: FUNCTION KEY 1,
                  FUNCTION KEY 2.

SELECTION-SCREEN BEGIN OF SCREEN 9010 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b01 WITH FRAME TITLE TEXT-001.
    SELECT-OPTIONS: smatnr FOR mara-matnr,
                    smbrsh FOR mara-mbrsh NO INTERVALS NO-EXTENSION ,
                    smtart FOR mara-mtart,
                    swerks FOR marc-werks,
                    slgort FOR mard-lgort.
  SELECTION-SCREEN END OF BLOCK b01.
SELECTION-SCREEN END OF SCREEN 9010.

SELECTION-SCREEN BEGIN OF SCREEN 9020 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b04 WITH FRAME.
    SELECTION-SCREEN BEGIN OF BLOCK b03 WITH FRAME TITLE TEXT-002.
      SELECTION-SCREEN BEGIN OF LINE.
        SELECTION-SCREEN COMMENT 1(20) TEXT-006 ##TEXT_POOL.
        PARAMETERS: rb_f1 RADIOBUTTON GROUP rg01 DEFAULT 'X' USER-COMMAND zd1.
        SELECTION-SCREEN COMMENT 33(25) TEXT-003 FOR FIELD rb_f1.
        PARAMETERS: rb_f2 RADIOBUTTON GROUP rg01.
        SELECTION-SCREEN COMMENT 64(26) TEXT-004 FOR FIELD rb_f2.
      SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN END OF BLOCK b03.

    SELECTION-SCREEN SKIP 1.
    SELECTION-SCREEN BEGIN OF BLOCK b02 WITH FRAME TITLE TEXT-005.
      PARAMETERS: pfile TYPE rlgrap-filename MODIF ID b1. " Nam add MODIF ID B1
    SELECTION-SCREEN END OF BLOCK b02.
  SELECTION-SCREEN END OF BLOCK b04.
SELECTION-SCREEN END OF SCREEN 9020.

SELECTION-SCREEN BEGIN OF TABBED BLOCK mytab FOR 15 LINES.
  SELECTION-SCREEN TAB (20) button1 USER-COMMAND push1.
  SELECTION-SCREEN TAB (20) button2 USER-COMMAND push2.
SELECTION-SCREEN END OF BLOCK mytab.
